### ISSUE TITLE
Style updates

### ISSUE THREAD

**Issue by mmarol** [risd/risd-compliance-bridge#1]
@rubillionaire here's a list of updates to make:
- [x] change the yellow across the page to this blue `#0F74E6`
- [x] change the color of the type and icon and logo in the nav to white
- [x] add a max-width to the page description of `40em`
- [x] remove the `Index` column and the tooltip in the `Policy` columns
- [x] update the nav to reflect the mockups in figma. We haven't landed on exactly the items will be but there will be a couple of phases at least, just one category to start with and then the rest at a later date.

Mockups:
https://www.figma.com/file/2QhOLeCpKfBQsK96nbseJe/Untitled?node-id=0%3A1

**Comment by rubillionaire** [comment]
thanks for the list, @mmarol, i've got a first draft up here: http://compliance-bridge.risd.systems/

let me know how it looks

**Comment by rubillionaire** [comment]
this has been delivered to compliance bridge, so im going to close up the issue for now.
